name: linux
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: linux

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.82
        target: x86_64-unknown-linux-gnu
        components: clippy

    - name: Run Tests
      run: |
        cargo test

    - name: Clippy Checks
      run: |
        rustup component add clippy
        cargo clippy --workspace --tests --all-features -- -D warnings

    - name: Check for Unused Dependencies
      run: |
        cargo install cargo-machete@0.7.0
        cargo machete
